version: '3'

services:

    api:
<<<<<<< HEAD
     container_name: api-openhostal-dock
=======
     container_name: api-movie-dock
>>>>>>> 39e61b5e994c40422e69a986eef44630543c365e
     restart: always
     build: .
     ports:
      - 4000:3015

     links:
      - mongo
<<<<<<< HEAD
      - postgres

    mongo:
        container_name: mongoDB1
        image: mongo
        ports:
          - 27022:27017 
    postgres:
        image: postgres
        environment: 
          - DATABASE_HOST=localhost     
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=12345
          - POSTGRES_DB=openhostel
        ports: 
          - 5432:5432
    pgadmin:
        image: dpage/pgadmin4
        environment: 
          PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
          PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
          - "5050:80"
        depends_on: 
          - postgres 
=======

    mongo:
        container_name: mongoDB
        image: mongo
        ports:
          - 27022:27017 
>>>>>>> 39e61b5e994c40422e69a986eef44630543c365e
