version: '3'

services:

    api:
     container_name: api-openhostal-dock
     restart: always
     build: .
     ports:
      - 4000:3015

     links:
      - mongo

    mongo:
        container_name: mongoDB1
        image: mongo
        ports:
          - 27022:27017 
